# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('Type', models.IntegerField(default=1, verbose_name='тип конкурса')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('Approved', models.BooleanField(default=False, verbose_name='принят')),
                ('competition_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participates_competition', to='vote.Competition', verbose_name='конкурс')),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_competition', to='vote.Competition')),
                ('participate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_participate', to='vote.Participate')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='poll',
            unique_together=set([('competition', 'participate')]),
        ),
    ]
