# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='Type',
            field=models.IntegerField(choices=[(1, 'Фотоконкурс'), (2, 'Литературный конкурс'), (3, 'Видеоконкурс'), (4, 'Аудиоконкурс')], default=1, verbose_name='тип конкурса'),
        ),
    ]
