# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-13 12:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competition_user', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participate',
            name='Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participate_user', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='Survey_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 18, 12, 4, 54, 967668, tzinfo=utc), verbose_name='опрос с'),
        ),
    ]
