# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-13 12:41
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='rules',
            field=ckeditor.fields.RichTextField(max_length=2000, verbose_name='правила'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='short_description',
            field=ckeditor.fields.RichTextField(max_length=500, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='survey_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 12, 41, 31, 909570, tzinfo=utc), verbose_name='опрос с'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='comment',
            field=ckeditor.fields.RichTextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='content',
            field=models.FileField(upload_to='uploads/', verbose_name='файл'),
        ),
    ]
