# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-08 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180218_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='survey_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 9, 53, 29, 613090, tzinfo=utc), verbose_name='опрос с'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='content',
            field=models.FileField(upload_to='uploads/', verbose_name='файл'),
        ),
    ]
