# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-01 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20180402_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='survey_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 6, 14, 59, 29, 344407, tzinfo=utc), verbose_name='голосование с'),
        ),
    ]
