# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20180403_0935'),
        ('vote', '0003_auto_20180402_0059'),
    ]

    operations = [
    ]
