# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_competition_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='participate',
            name='Approved',
        ),
        migrations.AddField(
            model_name='participate',
            name='Content',
            field=models.FileField(default=1, upload_to='documents/', verbose_name='файл'),
            preserve_default=False,
        ),
    ]
