# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-17 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20180217_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='survey_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 22, 14, 40, 22, 545495, tzinfo=utc), verbose_name='опрос с'),
        ),
    ]
