# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20180204_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='Comment',
            field=models.TextField(default=1, verbose_name='комментарий'),
            preserve_default=False,
        ),
    ]
