# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-03 07:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import vote.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_merge_20180403_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='survey_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 8, 7, 0, 37, 334515, tzinfo=utc), verbose_name='голосование с'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[vote.validators.validate_file_extension], verbose_name='файл'),
        ),
    ]
