# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-06 11:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20180403_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='survey_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 11, 11, 55, 36, 783678, tzinfo=utc), verbose_name='голосование с'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='файл'),
        ),
    ]
